### PR TITLE
Force iland API v0.8.

### PR DESCRIPTION
**Pull request by anguenot**

### CODE REVIEW

**Comment by anguenot** [comment]
@bsnyder788  @cfsnyder  good to go?

**Comment by cfsnyder** [comment]
Yeah, are you gonna create a 0.8 tag too?

**Comment by anguenot** [comment]
@cfsnyder  would like to wait for us to align version to 1.0 as discussed. Making sense?

**Comment by cfsnyder** [comment]
As long as nobody outside of iland is using it, I guess it doesn’t really matter.

**Comment by anguenot** [comment]
@cfsnyder  well they could still be using the previous release version of pypi correct?

**Pull request merged**
